server:
  port: 8000

spring:
  profiles:
    active: auth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
      format_sql: true
  jwt:
    secret: govlepel@$&
  messages:
    basename: i18n/exception
    encoding: UTF-8
  url:
    base: https://i3a606.p.ssafy.io
    #base: http://localhost:8090

  logging:
    level: info

mybatis:
  config-location: classpath:config/mybatis-config.xml