spring:
  profiles: auth
  datasource:
    url: jdbc:mysql://i3a606.p.ssafy.io:3306/locker?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: com.ssafy.Locker@gmail.com
    password: 1q2w3e4r!@
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  social:
    kakao:
      client_id: b61dc6eae6d4f924c15b4499b65c993e # 앱생성시 받은 REST API 키
      redirect: /api/social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 858388202728-f26u33io27sn79ic2ac789sc03ht9vuf.apps.googleusercontent.com
            clientSecret: Ype18wpAoTZ8sxzR9XzsMQfv
            redirectUri: http://localhost:8090/api/social/login/google
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            scope:
              - email
              - public_profile
          github:
            clientId: c073047a7c28dc98f6c4
            clientSecret: b8753e6376a96acbab93f536caf52de6df3e856f
            redirectUri: http://localhost:8090/api/social/login/github
            scope:
              - user:email
              - read:user
